### ISSUE TITLE
AbstractMethodError pl.projectspace.idea.plugins.php.behat.BehatJavaExtension.getDataObject

### ISSUE THREAD

**Issue by dready** [mprzytulski/phpstorm-behat#34]
with latest eap and latest plugin i get an Exception:

```
pl.projectspace.idea.plugins.php.behat.BehatJavaExtension.getDataObject(Lcom/intellij/openapi/project/Project;)Ljava/lang/Object;: pl.projectspace.idea.plugins.php.behat.BehatJavaExtension.getDataObject(Lcom/intellij/openapi/project/Project;)Ljava/lang/Object;
java.lang.AbstractMethodError: pl.projectspace.idea.plugins.php.behat.BehatJavaExtension.getDataObject(Lcom/intellij/openapi/project/Project;)Ljava/lang/Object;
    at org.jetbrains.plugins.cucumber.steps.CucumberStepsIndex.<init>(CucumberStepsIndex.java:45)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
    at com.intellij.openapi.components.impl.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.initializeInstance(ServiceManagerImpl.java:159)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter$1.compute(ServiceManagerImpl.java:147)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:934)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:139)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:225)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:212)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:199)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:40)
    at org.jetbrains.plugins.cucumber.steps.CucumberStepsIndex.getInstance(CucumberStepsIndex.java:33)
    at pl.projectspace.idea.plugins.php.behat.BehatJavaExtension.resolveStep(BehatJavaExtension.java:99)
    at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.multiResolve(CucumberStepReference.java:86)
    at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.resolve(CucumberStepReference.java:42)
    at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:315)
    at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:203)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:97)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:355)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:346)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:343)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:319)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:194)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by eugenegp** [comment]
get the same Exception in PhpStorm-133.326 and plugins phpstorm-behat - 0.4, phpstorm-phpspec - 0.2

**Comment by anton-kasperovich** [comment]
+1, PhpStorm 7.0 build 131.374

**Comment by svanpoeck** [comment]
Hi,
I'm getting the same error with PhpStorm-136.1575 and plugin phpstorm-behat-0.4. I don't have phpspec plugin installed.

Thanks for your work!
