### ISSUE TITLE
Argument 1 for @NotNull parameter of com/intellij/psi/search/GlobalSearchScopesCore.directoryScope

### ISSUE THREAD

**Issue by oleg-andreyev** [mprzytulski/phpstorm-behat#35]
```
Argument 1 for @NotNull parameter of com/intellij/psi/search/GlobalSearchScopesCore.directoryScope must not be null: Argument 1 for @NotNull parameter of com/intellij/psi/search/GlobalSearchScopesCore.directoryScope must not be null
java.lang.IllegalArgumentException: Argument 1 for @NotNull parameter of com/intellij/psi/search/GlobalSearchScopesCore.directoryScope must not be null
    at com.intellij.psi.search.GlobalSearchScopesCore.directoryScope(GlobalSearchScopesCore.java)
    at pl.projectspace.idea.plugins.php.behat.feature.step.BehatStepReferenceProvider.getReferencesByElement(BehatStepReferenceProvider.java:49)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:122)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:65)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:53)
    at org.jetbrains.plugins.cucumber.psi.impl.GherkinStepImpl.getReferences(GherkinStepImpl.java:88)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.a(SharedPsiElementImplUtil.java:67)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:49)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:63)
    at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:88)
    at com.intellij.psi.SingleRootFileViewProvider.a(SingleRootFileViewProvider.java:423)
```

**Comment by eugenegp** [comment]
```
Argument 1 for @NotNull parameter of com/intellij/psi/search/GlobalSearchScopesCore.directoryScope must not be null: Argument 1 for @NotNull parameter of com/intellij/psi/search/GlobalSearchScopesCore.directoryScope must not be null
java.lang.IllegalArgumentException: Argument 1 for @NotNull parameter of com/intellij/psi/search/GlobalSearchScopesCore.directoryScope must not be null
    at com.intellij.psi.search.GlobalSearchScopesCore.directoryScope(GlobalSearchScopesCore.java)
    at pl.projectspace.idea.plugins.php.behat.feature.step.BehatStepReferenceProvider.getReferencesByElement(BehatStepReferenceProvider.java:49)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:122)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:65)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:53)
    at org.jetbrains.plugins.cucumber.psi.impl.GherkinStepImpl.getReferences(GherkinStepImpl.java:88)
    at org.jetbrains.plugins.cucumber.inspections.CucumberStepInspection$1.visitStep(CucumberStepInspection.java:60)
    at org.jetbrains.plugins.cucumber.psi.impl.GherkinStepImpl.acceptGherkin(GherkinStepImpl.java:92)
    at org.jetbrains.plugins.cucumber.psi.impl.GherkinPsiElementBase.accept(GherkinPsiElementBase.java:81)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:74)
    at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:358)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:75)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$3.process(LocalInspectionsPass.java:327)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$3.process(LocalInspectionsPass.java:324)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:119)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:103)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by Guibod** [comment]
The plugin don't seem to work without a behat.yml file located in root directory of the project.

In my case, behat.yml is located in test/bdd/ directory and trigger the same error.
I was able to start using the plugin before another crash by starting a new PHPStorm subproject in my test/bdd/ directory.

**Comment by bendavies** [comment]
doesn't work at all for me. behat.yml is in the project root.

**Comment by Floyd25** [comment]
Same Problem here. My behat.yml is also quite deep inside my project's directory structure.
So I copied it to project root and the Error Message was gone. it used to pop up every time I just opened my project in phpstorm.
But: When I start to edit a Feature-File the error message is back. Besides that: The Context-Options "Create new context" etc using File templates also isn't showing up in the Menu.

**Comment by dready** [comment]
like bendavies, behat.yml is always in the project root. null pointer exception..

**Comment by nike-17** [comment]
same problem - behat.yml in the root folder, but I still got this messages

**Comment by ralfstrobel** [comment]
I can also confirm these NPEs in Version 0.4, PHPStorm 7.1.2. Real shame, this plugin seems awesome otherwise.

**Comment by robo47** [comment]
Same Error here

Version: 0.4
PHPStorm: 7.1.3 on Ubuntu
behat.yml is in root directory

**Comment by ghost** [comment]
Same issue
Version 0.4
PHPStorm: 7.1.3 on OS X 10.9.4

**Comment by rubencougil** [comment]
same issue here 
behat 2.4.0
phpstorm: 2016.2.2
